import {
  Accessibility,
  Activity,
  Ambulance,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Award,
  Baby,
  BadgeCheck,
  Bone,
  Brain,
  Building,
  CalendarCheck,
  CalendarDays,
  Camera,
  Car,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  CircleHelp,
  Clock,
  Coffee,
  Cpu,
  CreditCard,
  Crown,
  Droplet,
  Ear,
  Eye,
  Facebook,
  FileText,
  Gem,
  Globe,
  GraduationCap,
  Heart,
  HeartHandshake,
  HeartPulse,
  Home,
  Hospital,
  Info,
  Instagram,
  Languages,
  Layers,
  Leaf,
  Lightbulb,
  Linkedin,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  Microscope,
  Minus,
  Moon,
  Navigation,
  Phone,
  PhoneCall,
  Pill,
  Play,
  Plus,
  Quote,
  Scan,
  Send,
  Shield,
  ShieldCheck,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  Syringe,
  Target,
  Thermometer,
  Timer,
  TrendingUp,
  Truck,
  Twitter,
  UserRound,
  Users,
  Video,
  Wallet,
  Waves,
  Wifi,
  X,
  Youtube,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/**
 * A curated icon registry.
 *
 * `clinic.json` references icons by name (`"icon": "HeartPulse"`), which keeps
 * content authoring free of imports. The registry is explicit rather than a
 * `import * as icons` barrel so the bundle only ever ships these ~85 icons
 * instead of the full 1,500-icon library.
 *
 * Adding an icon = add the import and the map entry. Nothing else changes.
 */
export const ICONS = {
  Accessibility,
  Activity,
  Ambulance,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Award,
  Baby,
  BadgeCheck,
  Bone,
  Brain,
  Building,
  CalendarCheck,
  CalendarDays,
  Camera,
  Car,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  CircleHelp,
  Clock,
  Coffee,
  Cpu,
  CreditCard,
  Crown,
  Droplet,
  Ear,
  Eye,
  Facebook,
  FileText,
  Gem,
  Globe,
  GraduationCap,
  Heart,
  HeartHandshake,
  HeartPulse,
  Home,
  Hospital,
  Info,
  Instagram,
  Languages,
  Layers,
  Leaf,
  Lightbulb,
  Linkedin,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  Microscope,
  Minus,
  Moon,
  Navigation,
  Phone,
  PhoneCall,
  Pill,
  Play,
  Plus,
  Quote,
  Scan,
  Send,
  Shield,
  ShieldCheck,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  Syringe,
  Target,
  Thermometer,
  Timer,
  TrendingUp,
  Truck,
  Twitter,
  UserRound,
  Users,
  Video,
  Wallet,
  Waves,
  Wifi,
  X,
  Youtube,
  Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

/** Case- and dash-insensitive lookup: `heart-pulse`, `heartPulse`, `HeartPulse`. */
const LOOKUP = new Map<string, LucideIcon>(
  Object.entries(ICONS).map(([name, icon]) => [name.toLowerCase(), icon]),
);

export function getIcon(name?: string | null, fallback: LucideIcon = Sparkles): LucideIcon {
  if (!name) return fallback;
  const normalised = name.replace(/[-_\s]/g, '').toLowerCase();
  return LOOKUP.get(normalised) ?? fallback;
}

/** Returns `undefined` (rather than a fallback) so callers can skip rendering. */
export function getOptionalIcon(name?: string | null): LucideIcon | undefined {
  if (!name) return undefined;
  return LOOKUP.get(name.replace(/[-_\s]/g, '').toLowerCase());
}

export const SOCIAL_ICONS: Record<string, LucideIcon> = {
  facebook: Facebook,
  instagram: Instagram,
  x: Twitter,
  twitter: Twitter,
  linkedin: Linkedin,
  youtube: Youtube,
  tiktok: Video,
  whatsapp: MessageCircle,
  google: Globe,
};

export const SOCIAL_LABELS: Record<string, string> = {
  facebook: 'Facebook',
  instagram: 'Instagram',
  x: 'X',
  twitter: 'Twitter',
  linkedin: 'LinkedIn',
  youtube: 'YouTube',
  tiktok: 'TikTok',
  whatsapp: 'WhatsApp',
  google: 'Google Business Profile',
};

export type { LucideIcon };
